### ISSUE TITLE
missing CsDebugScript.UI.tlb

### ISSUE THREAD

**Issue by JianwenSun** [southpolenator/WinDbgCs#10]
![image](https://user-images.githubusercontent.com/8909264/28198005-7053018e-688d-11e7-9970-c0b7e2e78937.png)

![image](https://user-images.githubusercontent.com/8909264/28198000-67e903e0-688d-11e7-949a-11fd6b1251c1.png)

**Comment by southpolenator** [comment]
There is a post build event in CsDebugScript.UI.csproj file that calls tlbexp and generates tlb file.
Here is an example on the usage: https://docs.microsoft.com/en-us/dotnet/framework/tools/tlbexp-exe-type-library-exporter
Project build event actually just calls: tlbexp CsDebugScript.UI.dll
